package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/use-golang/api/graph/model"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, name string) (*model.Room, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, fmt.Errorf("room name cannot be empty")
	}

	room := &model.Room{
		ID:   fmt.Sprintf("room-%d", time.Now().UnixNano()),
		Name: name,
	}
	return r.DB.CreateRoom(ctx, room)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, room string, sender string, text string) (*model.Message, error) {
	msg := &model.Message{
		ID:        fmt.Sprintf("%d", time.Now().UnixNano()),
		Room:      room,
		Sender:    sender,
		Text:      text,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Upvotes:   0,
	}

	if err := r.DB.SaveMessage(ctx, msg); err != nil {
		return nil, fmt.Errorf("failed to save message: %w", err)
	}

	// Fan-out to chat subscribers.
	r.mu.Lock()
	for _, sub := range r.subscribers {
		if sub.room == room {
			select {
			case sub.ch <- msg:
			default:
			}
		}
	}
	r.mu.Unlock()

	// Enqueue async job for this message.
	if r.InsertJob != nil {
		if err := r.InsertJob(msg.ID); err != nil {
			log.Printf("Failed to enqueue job for message %s: %v", msg.ID, err)
		}
	}

	return msg, nil
}

// SurpriseMe is the resolver for the surpriseMe field.
func (r *mutationResolver) SurpriseMe(ctx context.Context, room string, sender string, text string) (*model.Message, error) {
	msg := &model.Message{
		ID:        fmt.Sprintf("%d", time.Now().UnixNano()),
		Room:      room,
		Sender:    sender,
		Text:      text,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Upvotes:   0,
	}

	if err := r.DB.SaveMessage(ctx, msg); err != nil {
		return nil, fmt.Errorf("failed to save message: %w", err)
	}

	// Fan-out to chat subscribers so the message appears in real-time for everyone.
	r.mu.Lock()
	for _, sub := range r.subscribers {
		if sub.room == room {
			select {
			case sub.ch <- msg:
			default:
			}
		}
	}
	r.mu.Unlock()

	// Enqueue the surprise_upvote job.
	if r.InsertSurpriseJob != nil {
		if err := r.InsertSurpriseJob(msg.ID); err != nil {
			log.Printf("Failed to enqueue surprise job for message %s: %v", msg.ID, err)
		}
	}

	return msg, nil
}

// SubmitCalorieQuery is the resolver for the submitCalorieQuery field.
func (r *mutationResolver) SubmitCalorieQuery(ctx context.Context, mealText string, modelName string, reasoningEffort *string) (*model.CalorieQuery, error) {
	mealText = strings.TrimSpace(mealText)
	if mealText == "" {
		return nil, fmt.Errorf("meal text cannot be empty")
	}

	q := &model.CalorieQuery{
		ID:              fmt.Sprintf("%d", time.Now().UnixNano()),
		MealText:        mealText,
		Model:           modelName,
		ReasoningEffort: reasoningEffort,
		Status:          "pending",
		CreatedAt:       time.Now().UTC().Format(time.RFC3339),
	}

	if err := r.DB.SaveCalorieQuery(ctx, q); err != nil {
		return nil, fmt.Errorf("failed to save calorie query: %w", err)
	}

	if r.InsertCalorieJob != nil {
		if err := r.InsertCalorieJob(q.ID); err != nil {
			log.Printf("Failed to enqueue calorie job for query %s: %v", q.ID, err)
		}
	}

	return q, nil
}

// ClearCalorieQueries is the resolver for the clearCalorieQueries field.
func (r *mutationResolver) ClearCalorieQueries(ctx context.Context) (bool, error) {
	if err := r.DB.DeleteAllCalorieQueries(ctx); err != nil {
		return false, fmt.Errorf("failed to clear calorie queries: %w", err)
	}
	return true, nil
}

// DeleteCalorieQuery is the resolver for the deleteCalorieQuery field.
func (r *mutationResolver) DeleteCalorieQuery(ctx context.Context, id string) (bool, error) {
	if err := r.DB.DeleteCalorieQuery(ctx, id); err != nil {
		return false, fmt.Errorf("failed to delete calorie query: %w", err)
	}
	return true, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	return r.DB.GetRooms(ctx)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, room string) ([]*model.Message, error) {
	return r.DB.GetMessages(ctx, room)
}

// CalorieQueries is the resolver for the calorieQueries field.
func (r *queryResolver) CalorieQueries(ctx context.Context) ([]*model.CalorieQuery, error) {
	return r.DB.GetCalorieQueries(ctx)
}

// MessageSent is the resolver for the messageSent field.
func (r *subscriptionResolver) MessageSent(ctx context.Context, room string) (<-chan *model.Message, error) {
	ch := make(chan *model.Message, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.subscribers[id] = &subscriber{room: room, ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.subscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// JobCompleted is the resolver for the jobCompleted field.
func (r *subscriptionResolver) JobCompleted(ctx context.Context, room string, sender string) (<-chan *model.JobResult, error) {
	ch := make(chan *model.JobResult, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.jobSubscribers[id] = &jobSubscriber{room: room, sender: sender, ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.jobSubscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// SurpriseUpvoteCompleted is the resolver for the surpriseUpvoteCompleted field.
func (r *subscriptionResolver) SurpriseUpvoteCompleted(ctx context.Context, room string) (<-chan *model.Message, error) {
	ch := make(chan *model.Message, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.surpriseSubscribers[id] = &surpriseSubscriber{room: room, ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.surpriseSubscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// CalorieQueryCompleted is the resolver for the calorieQueryCompleted field.
func (r *subscriptionResolver) CalorieQueryCompleted(ctx context.Context) (<-chan *model.CalorieQuery, error) {
	ch := make(chan *model.CalorieQuery, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.calorieSubscribers[id] = &calorieSubscriber{ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.calorieSubscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
