package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/gotesting/api/graph/model"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, name string) (*model.Room, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, fmt.Errorf("room name cannot be empty")
	}

	room := &model.Room{
		ID:   fmt.Sprintf("room-%d", time.Now().UnixNano()),
		Name: name,
	}
	return r.DB.CreateRoom(ctx, room)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, room string, sender string, text string) (*model.Message, error) {
	msg := &model.Message{
		ID:        fmt.Sprintf("%d", time.Now().UnixNano()),
		Room:      room,
		Sender:    sender,
		Text:      text,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}

	if err := r.DB.SaveMessage(ctx, msg); err != nil {
		return nil, fmt.Errorf("failed to save message: %w", err)
	}

	// Fan-out to chat subscribers.
	r.mu.Lock()
	for _, sub := range r.subscribers {
		if sub.room == room {
			select {
			case sub.ch <- msg:
			default:
			}
		}
	}
	r.mu.Unlock()

	// Enqueue async job for this message.
	if r.InsertJob != nil {
		if err := r.InsertJob(msg.ID); err != nil {
			log.Printf("Failed to enqueue job for message %s: %v", msg.ID, err)
		}
	}

	return msg, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	return r.DB.GetRooms(ctx)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, room string) ([]*model.Message, error) {
	return r.DB.GetMessages(ctx, room)
}

// MessageSent is the resolver for the messageSent field.
func (r *subscriptionResolver) MessageSent(ctx context.Context, room string) (<-chan *model.Message, error) {
	ch := make(chan *model.Message, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.subscribers[id] = &subscriber{room: room, ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.subscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// JobCompleted is the resolver for the jobCompleted field.
func (r *subscriptionResolver) JobCompleted(ctx context.Context, room string, sender string) (<-chan *model.JobResult, error) {
	ch := make(chan *model.JobResult, 1)

	r.mu.Lock()
	id := r.nextID
	r.nextID++
	r.jobSubscribers[id] = &jobSubscriber{room: room, sender: sender, ch: ch}
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.jobSubscribers, id)
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
